### PR TITLE
Add catchall for per-page processing errs

### LINKED ISSUE #5: Converter Failing on a Page
I'm getting this error:
```
!!WARNING!! Page Failed: C:\Users\jason\Desktop\OneNoteExport\Jason_K_s_Notebook\Health\015_Enneagram_Personality_Result___Type_4w3.md
!!WARNING!! Page Failed: C:\Users\jason\Desktop\OneNoteExport\Jason_K_s_Notebook\Health\016_Five_Minute_Journal___Daily_Journal_Techniques_and_Tips.md
!!WARNING!! Page Failed: C:\Users\jason\Desktop\OneNoteExport\Jason_K_s_Notebook\Health\017_Vaccination_Card_3_shots.md
Traceback (most recent call last):
  File "C:\Users\jason\GitHub\onenote-to-markdown\convert.py", line 121, in <module>
    handle_element(onenote, child)
  File "C:\Users\jason\GitHub\onenote-to-markdown\convert.py", line 101, in handle_element
    handle_element(onenote, c2, os.path.join(path, safe_str(elem.attrib['name'])), i)
  File "C:\Users\jason\GitHub\onenote-to-markdown\convert.py", line 103, in handle_element
    hier2 = onenote.GetHierarchy(elem.attrib['ID'], win32.constants.hsPages, "")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\AppData\Local\Temp\gen_py\3.11\F2A7EE29-8BF6-4A6D-83F1-098E366C709Cx0x1x0\IApplication.py", line 63, in GetHierarchy
    return self._ApplyTypes_(1610743808, 1, (24, 0), ((8, 1), (3, 1), (16392, 2)), 'GetHierarchy', None,bstrStartNodeID
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason\GitHub\onenote-to-markdown\.venv\Lib\site-packages\win32com\client\__init__.py", line 572, in _ApplyTypes_
    self._oleobj_.InvokeTypes(dispid, 0, wFlags, retType, argTypes, *args),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147023174, 'The RPC server is unavailable.', None, None)
!!!Error!!! Hint: Make sure OneNote is open first.
```

OneNote is open but something causes it to close causing the RPC error. Nothing gets written the desktop either. 

There needs to be some error handling. I'm reviewing the youtube video and seeing if I need to clear anything. I'm using OneNote for Windows 11 and everything is updated.

### PR DESCRIPTION
**Pull request by stephengrice**

### CODE REVIEW

**Comment by jkbellew** [comment]
I just got the RPC server is unavailable when I know that OneNote is open. I'll take a stab at it this weekend, and even try playing with the PowerShell version.

**Comment by stephengrice** [comment]
Going to merge this in but keep #5 open. I haven't had much luck reproducing the errors people are reporting on this, so sorry if I haven't been much help. I don't use OneNote anymore so I only have it running in a VM

**Comment by jkbellew** [comment]
I'm experiencing OneNote closing (crashing?) and then re-opening. It's not happening at the same place every time either. 

Maybe why you can't reproduce.

Also, I have a very large notebook and I'm wondering if that has anything to do with the issue. I'm going to experiment with different sizes and see what comes of that.

**Comment by stephengrice** [comment]
> I'm experiencing OneNote closing (crashing?) and then re-opening. It's not happening at the same place every time either.
> 
> Maybe why you can't reproduce.
> 
> Also, I have a very large notebook and I'm wondering if that has anything to do with the issue. I'm going to experiment with different sizes and see what comes of that.

Sounds good! Hope it goes well. That definitely might be part of it. Since I migrated my huge OneNote notebook out, I've been doing all my testing on minimal notebooks with just a few pages.

**Pull request merged**
